import {
  type User,
  type Classroom,
  type ExamSession,
  type DetectionEvent,
  type Case,
  type TimelineEntry,
  type ThresholdConfig,
  type AuditLogEntry,
  type Notification,
  type ExamScheduleEntry,
  type InvigilatorAssignment,
  type SeatPolygon,
  Role,
  CaseStatus,
  BehaviorType,
  PenaltyType,
  AppealStatus,
  SessionStatus,
} from './types';

// ═══════════════════════════════════════════
// Realistic fixture data for ProctorAI
// Pakistani university context
// ═══════════════════════════════════════════

// ── Users ──────────────────────────────────

export const users: User[] = [
  // Admin
  {
    id: 'usr-001',
    name: 'Dr. Sadia Rashid',
    email: 'sadia.rashid@au.edu.pk',
    role: Role.Admin,
    department: 'IT Services',
    status: 'Active',
    createdAt: '2025-08-15T09:00:00Z',
  },
  // HODs
  {
    id: 'usr-002',
    name: 'Prof. Khalid Mehmood',
    email: 'khalid.mehmood@au.edu.pk',
    role: Role.HOD,
    department: 'Computer Science',
    status: 'Active',
    createdAt: '2025-08-15T09:00:00Z',
  },
  {
    id: 'usr-003',
    name: 'Dr. Ayesha Farooq',
    email: 'ayesha.farooq@au.edu.pk',
    role: Role.HOD,
    department: 'Software Engineering',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  // Teachers
  {
    id: 'usr-004',
    name: 'Mr. Usman Tariq',
    email: 'usman.tariq@au.edu.pk',
    role: Role.Teacher,
    department: 'Computer Science',
    status: 'Active',
    createdAt: '2025-08-20T09:00:00Z',
  },
  {
    id: 'usr-005',
    name: 'Ms. Fatima Zahra',
    email: 'fatima.zahra@au.edu.pk',
    role: Role.Teacher,
    department: 'Computer Science',
    status: 'Active',
    createdAt: '2025-08-20T09:00:00Z',
  },
  {
    id: 'usr-006',
    name: 'Dr. Hassan Ali',
    email: 'hassan.ali@au.edu.pk',
    role: Role.Teacher,
    department: 'Software Engineering',
    status: 'Active',
    createdAt: '2025-08-25T09:00:00Z',
  },
  {
    id: 'usr-007',
    name: 'Ms. Nadia Bukhari',
    email: 'nadia.bukhari@au.edu.pk',
    role: Role.Teacher,
    department: 'Computer Science',
    status: 'Inactive',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-008',
    name: 'Mr. Bilal Asghar',
    email: 'bilal.asghar@au.edu.pk',
    role: Role.Teacher,
    department: 'Software Engineering',
    status: 'Active',
    createdAt: '2025-09-10T09:00:00Z',
  },
  // Exam Controller
  {
    id: 'usr-009',
    name: 'Mr. Naveed Iqbal',
    email: 'naveed.iqbal@au.edu.pk',
    role: Role.ExamController,
    department: 'Examination Branch',
    status: 'Active',
    createdAt: '2025-08-15T09:00:00Z',
  },
  // Students
  {
    id: 'usr-010',
    name: 'Ahmed Raza',
    email: 'ahmed.raza@student.au.edu.pk',
    role: Role.Student,
    department: 'Computer Science',
    registrationNo: '2022-CS-114',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-011',
    name: 'Zainab Malik',
    email: 'zainab.malik@student.au.edu.pk',
    role: Role.Student,
    department: 'Computer Science',
    registrationNo: '2022-CS-089',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-012',
    name: 'Omar Farooq',
    email: 'omar.farooq@student.au.edu.pk',
    role: Role.Student,
    department: 'Software Engineering',
    registrationNo: '2022-SE-042',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-013',
    name: 'Hira Nawaz',
    email: 'hira.nawaz@student.au.edu.pk',
    role: Role.Student,
    department: 'Computer Science',
    registrationNo: '2023-CS-201',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-014',
    name: 'Ali Hassan Shah',
    email: 'ali.shah@student.au.edu.pk',
    role: Role.Student,
    department: 'Computer Science',
    registrationNo: '2022-CS-156',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-015',
    name: 'Maryam Asif',
    email: 'maryam.asif@student.au.edu.pk',
    role: Role.Student,
    department: 'Software Engineering',
    registrationNo: '2023-SE-018',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-016',
    name: 'Hamza Qureshi',
    email: 'hamza.qureshi@student.au.edu.pk',
    role: Role.Student,
    department: 'Computer Science',
    registrationNo: '2022-CS-203',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-017',
    name: 'Sara Javed',
    email: 'sara.javed@student.au.edu.pk',
    role: Role.Student,
    department: 'Computer Science',
    registrationNo: '2023-CS-077',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-018',
    name: 'Talha Siddiqui',
    email: 'talha.siddiqui@student.au.edu.pk',
    role: Role.Student,
    department: 'Software Engineering',
    registrationNo: '2022-SE-091',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-019',
    name: 'Amna Rehman',
    email: 'amna.rehman@student.au.edu.pk',
    role: Role.Student,
    department: 'Computer Science',
    registrationNo: '2023-CS-145',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-020',
    name: 'Faizan Ahmad',
    email: 'faizan.ahmad@student.au.edu.pk',
    role: Role.Student,
    department: 'Computer Science',
    registrationNo: '2022-CS-067',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-021',
    name: 'Rabia Khan',
    email: 'rabia.khan@student.au.edu.pk',
    role: Role.Student,
    department: 'Software Engineering',
    registrationNo: '2023-SE-033',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'usr-022',
    name: 'Danyal Mirza',
    email: 'danyal.mirza@student.au.edu.pk',
    role: Role.Student,
    department: 'Computer Science',
    registrationNo: '2022-CS-188',
    status: 'Active',
    createdAt: '2025-09-01T09:00:00Z',
  },
];

// ── Classrooms ─────────────────────────────

const defaultSeatMap: SeatPolygon[] = Array.from({ length: 30 }, (_, i) => ({
  seatNumber: i + 1,
  vertices: [
    { x: (i % 6) * 100 + 20, y: Math.floor(i / 6) * 80 + 20 },
    { x: (i % 6) * 100 + 80, y: Math.floor(i / 6) * 80 + 20 },
    { x: (i % 6) * 100 + 80, y: Math.floor(i / 6) * 80 + 60 },
    { x: (i % 6) * 100 + 20, y: Math.floor(i / 6) * 80 + 60 },
  ],
}));

export const classrooms: Classroom[] = [
  {
    id: 'cls-001',
    name: 'LH-4',
    building: 'Block A',
    capacity: 60,
    cameraId: 'cam-001',
    cameraStatus: 'Online',
    seatMap: defaultSeatMap,
    createdAt: '2025-08-01T09:00:00Z',
  },
  {
    id: 'cls-002',
    name: 'LH-7',
    building: 'Block A',
    capacity: 45,
    cameraId: 'cam-002',
    cameraStatus: 'Online',
    seatMap: defaultSeatMap.slice(0, 20),
    createdAt: '2025-08-01T09:00:00Z',
  },
  {
    id: 'cls-003',
    name: 'CR-201',
    building: 'Block B',
    capacity: 30,
    cameraId: 'cam-003',
    cameraStatus: 'Online',
    seatMap: defaultSeatMap.slice(0, 15),
    createdAt: '2025-08-01T09:00:00Z',
  },
  {
    id: 'cls-004',
    name: 'LH-2',
    building: 'Block A',
    capacity: 80,
    cameraId: 'cam-004',
    cameraStatus: 'Offline',
    createdAt: '2025-08-01T09:00:00Z',
  },
  {
    id: 'cls-005',
    name: 'Lab-3',
    building: 'Block C',
    capacity: 40,
    cameraId: 'cam-005',
    cameraStatus: 'Maintenance',
    seatMap: defaultSeatMap.slice(0, 20),
    createdAt: '2025-08-15T09:00:00Z',
  },
  {
    id: 'cls-006',
    name: 'CR-105',
    building: 'Block A',
    capacity: 35,
    cameraId: 'cam-006',
    cameraStatus: 'Online',
    seatMap: defaultSeatMap.slice(0, 18),
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'cls-007',
    name: 'LH-9',
    building: 'Block B',
    capacity: 50,
    cameraId: 'cam-007',
    cameraStatus: 'Online',
    createdAt: '2025-09-01T09:00:00Z',
  },
  {
    id: 'cls-008',
    name: 'Seminar Hall',
    building: 'Main Block',
    capacity: 120,
    cameraId: 'cam-008',
    cameraStatus: 'Online',
    createdAt: '2025-09-15T09:00:00Z',
  },
  {
    id: 'cls-009',
    name: 'Lab-1',
    building: 'Block C',
    capacity: 30,
    cameraId: 'cam-009',
    cameraStatus: 'Online',
    seatMap: defaultSeatMap.slice(0, 15),
    createdAt: '2025-08-01T09:00:00Z',
  },
  {
    id: 'cls-010',
    name: 'CR-302',
    building: 'Block B',
    capacity: 25,
    cameraStatus: 'Offline',
    createdAt: '2025-09-20T09:00:00Z',
  },
];

// ── Exam Sessions ──────────────────────────

export const examSessions: ExamSession[] = [
  {
    id: 'ses-001',
    courseCode: 'CS-301',
    courseName: 'Database Systems',
    classroomId: 'cls-001',
    classroomName: 'LH-4',
    scheduledDate: '2026-09-22',
    startTime: '09:00',
    endTime: '12:00',
    status: SessionStatus.InProgress,
    invigilatorId: 'usr-004',
    invigilatorName: 'Mr. Usman Tariq',
    silentMode: true,
    totalSeats: 60,
    occupiedSeats: 48,
    alertCount: 7,
    caseCount: 3,
    createdAt: '2026-09-15T09:00:00Z',
  },
  {
    id: 'ses-002',
    courseCode: 'SE-410',
    courseName: 'Software Architecture',
    classroomId: 'cls-002',
    classroomName: 'LH-7',
    scheduledDate: '2026-09-22',
    startTime: '14:00',
    endTime: '17:00',
    status: SessionStatus.Scheduled,
    invigilatorId: 'usr-006',
    invigilatorName: 'Dr. Hassan Ali',
    silentMode: false,
    totalSeats: 45,
    occupiedSeats: 0,
    alertCount: 0,
    caseCount: 0,
    createdAt: '2026-09-15T09:00:00Z',
  },
  {
    id: 'ses-003',
    courseCode: 'CS-201',
    courseName: 'Data Structures',
    classroomId: 'cls-003',
    classroomName: 'CR-201',
    scheduledDate: '2026-09-20',
    startTime: '09:00',
    endTime: '12:00',
    status: SessionStatus.Completed,
    invigilatorId: 'usr-005',
    invigilatorName: 'Ms. Fatima Zahra',
    silentMode: true,
    totalSeats: 30,
    occupiedSeats: 28,
    alertCount: 12,
    caseCount: 5,
    createdAt: '2026-09-13T09:00:00Z',
  },
  {
    id: 'ses-004',
    courseCode: 'CS-401',
    courseName: 'Artificial Intelligence',
    classroomId: 'cls-001',
    classroomName: 'LH-4',
    scheduledDate: '2026-09-21',
    startTime: '14:00',
    endTime: '17:00',
    status: SessionStatus.Completed,
    invigilatorId: 'usr-004',
    invigilatorName: 'Mr. Usman Tariq',
    silentMode: false,
    totalSeats: 60,
    occupiedSeats: 55,
    alertCount: 4,
    caseCount: 2,
    createdAt: '2026-09-14T09:00:00Z',
  },
  {
    id: 'ses-005',
    courseCode: 'SE-320',
    courseName: 'Software Testing',
    classroomId: 'cls-005',
    classroomName: 'Lab-3',
    scheduledDate: '2026-09-23',
    startTime: '09:00',
    endTime: '11:00',
    status: SessionStatus.Scheduled,
    invigilatorId: 'usr-008',
    invigilatorName: 'Mr. Bilal Asghar',
    silentMode: true,
    totalSeats: 40,
    occupiedSeats: 0,
    alertCount: 0,
    caseCount: 0,
    createdAt: '2026-09-16T09:00:00Z',
  },
];

// ── Cases ──────────────────────────────────

const makeTimeline = (caseId: string, status: CaseStatus): TimelineEntry[] => {
  const base: TimelineEntry[] = [
    {
      id: `tl-${caseId}-1`,
      action: 'Detection event triggered',
      actorName: 'System',
      actorRole: Role.Admin,
      details: 'Automated behavior detection flagged this seat',
      timestamp: '2026-09-20T09:23:00Z',
    },
    {
      id: `tl-${caseId}-2`,
      action: 'Case created by invigilator',
      actorName: 'Mr. Usman Tariq',
      actorRole: Role.Teacher,
      details: 'Alert confirmed during live monitoring',
      timestamp: '2026-09-20T09:24:30Z',
    },
  ];

  if (status === CaseStatus.Confirmed || status === CaseStatus.Escalated) {
    base.push({
      id: `tl-${caseId}-3`,
      action: 'Case reviewed and confirmed',
      actorName: 'Prof. Khalid Mehmood',
      actorRole: Role.HOD,
      details: 'Evidence reviewed, behavior confirmed',
      timestamp: '2026-09-20T14:15:00Z',
    });
  }

  if (status === CaseStatus.Dismissed) {
    base.push({
      id: `tl-${caseId}-3`,
      action: 'Case dismissed',
      actorName: 'Prof. Khalid Mehmood',
      actorRole: Role.HOD,
      details: 'Insufficient evidence to proceed',
      timestamp: '2026-09-20T14:15:00Z',
    });
  }

  if (status === CaseStatus.Escalated) {
    base.push({
      id: `tl-${caseId}-4`,
      action: 'Case escalated to disciplinary committee',
      actorName: 'Prof. Khalid Mehmood',
      actorRole: Role.HOD,
      details: 'Multiple violations in single session, referred for further action',
      timestamp: '2026-09-20T16:30:00Z',
    });
  }

  return base;
};

export const cases: Case[] = [
  {
    id: 'case-001',
    referenceNo: 'AU-CS-INT-2026-001',
    sessionId: 'ses-003',
    studentId: 'usr-010',
    studentName: 'Ahmed Raza',
    studentRegNo: '2022-CS-114',
    courseCode: 'CS-201',
    courseName: 'Data Structures',
    classroomName: 'CR-201',
    seatNumber: 14,
    behaviourTypes: [BehaviorType.PhoneDetected, BehaviorType.GazeDeviation],
    compositeScore: 0.92,
    status: CaseStatus.Confirmed,
    detectionEventId: 'det-001',
    snapshotPath: '/snapshots/ses-003/det-001.jpg',
    teacherNote: 'Student was clearly using a phone under the desk. Confirmed visually.',
    teacherId: 'usr-005',
    teacherName: 'Ms. Fatima Zahra',
    hodId: 'usr-002',
    penalty: {
      id: 'pen-001',
      caseId: 'case-001',
      type: PenaltyType.ExamVoidance,
      description: 'Exam voided due to confirmed phone usage during examination. Student was observed using a mobile device concealed under the desk.',
      issuedBy: 'usr-002',
      issuedByName: 'Prof. Khalid Mehmood',
      noticeReference: 'AU-CS-INT-2026-001',
      createdAt: '2026-09-20T15:00:00Z',
    },
    appeal: {
      id: 'apl-001',
      caseId: 'case-001',
      studentId: 'usr-010',
      studentName: 'Ahmed Raza',
      studentRegNo: '2022-CS-114',
      statement: 'I was checking my insulin pump notification which is clipped to my waist. The device detected was medical equipment, not a phone. I can provide medical documentation from the university health center.',
      supportingInfo: 'Medical certificate from AU Health Center, ref: HC-2026-0847',
      status: AppealStatus.Open,
      submittedAt: '2026-09-21T10:00:00Z',
    },
    timeline: makeTimeline('case-001', CaseStatus.Confirmed),
    createdAt: '2026-09-20T09:24:30Z',
    updatedAt: '2026-09-21T10:00:00Z',
  },
  {
    id: 'case-002',
    referenceNo: 'AU-CS-INT-2026-002',
    sessionId: 'ses-003',
    studentId: 'usr-011',
    studentName: 'Zainab Malik',
    studentRegNo: '2022-CS-089',
    courseCode: 'CS-201',
    courseName: 'Data Structures',
    classroomName: 'CR-201',
    seatNumber: 7,
    behaviourTypes: [BehaviorType.GazeDeviation],
    compositeScore: 0.71,
    status: CaseStatus.Dismissed,
    detectionEventId: 'det-002',
    snapshotPath: '/snapshots/ses-003/det-002.jpg',
    teacherNote: 'Student appeared to be looking at the clock on the wall. False positive likely.',
    teacherId: 'usr-005',
    teacherName: 'Ms. Fatima Zahra',
    hodId: 'usr-002',
    timeline: makeTimeline('case-002', CaseStatus.Dismissed),
    createdAt: '2026-09-20T09:45:00Z',
    updatedAt: '2026-09-20T14:20:00Z',
  },
  {
    id: 'case-003',
    referenceNo: 'AU-CS-INT-2026-003',
    sessionId: 'ses-003',
    studentId: 'usr-013',
    studentName: 'Hira Nawaz',
    studentRegNo: '2023-CS-201',
    courseCode: 'CS-201',
    courseName: 'Data Structures',
    classroomName: 'CR-201',
    seatNumber: 22,
    behaviourTypes: [BehaviorType.LipMovement, BehaviorType.HeadPoseViolation],
    compositeScore: 0.84,
    status: CaseStatus.PendingReview,
    detectionEventId: 'det-003',
    snapshotPath: '/snapshots/ses-003/det-003.jpg',
    teacherNote: 'Observed lip movement during silent exam. Student appeared to be whispering.',
    teacherId: 'usr-005',
    teacherName: 'Ms. Fatima Zahra',
    timeline: makeTimeline('case-003', CaseStatus.PendingReview),
    createdAt: '2026-09-20T10:12:00Z',
    updatedAt: '2026-09-20T10:12:00Z',
  },
  {
    id: 'case-004',
    referenceNo: 'AU-SE-INT-2026-004',
    sessionId: 'ses-004',
    studentId: 'usr-012',
    studentName: 'Omar Farooq',
    studentRegNo: '2022-SE-042',
    courseCode: 'CS-401',
    courseName: 'Artificial Intelligence',
    classroomName: 'LH-4',
    seatNumber: 31,
    behaviourTypes: [BehaviorType.UnauthorisedObject],
    compositeScore: 0.88,
    status: CaseStatus.Confirmed,
    detectionEventId: 'det-004',
    snapshotPath: '/snapshots/ses-004/det-004.jpg',
    teacherNote: 'Unauthorized notes/cheat sheet detected on desk surface. Confiscated.',
    teacherId: 'usr-004',
    teacherName: 'Mr. Usman Tariq',
    hodId: 'usr-002',
    penalty: {
      id: 'pen-002',
      caseId: 'case-004',
      type: PenaltyType.FormalWarning,
      description: 'Formal warning issued for possession of unauthorized materials during examination.',
      issuedBy: 'usr-002',
      issuedByName: 'Prof. Khalid Mehmood',
      noticeReference: 'AU-SE-INT-2026-004',
      createdAt: '2026-09-21T16:00:00Z',
    },
    timeline: makeTimeline('case-004', CaseStatus.Confirmed),
    createdAt: '2026-09-21T14:35:00Z',
    updatedAt: '2026-09-21T16:00:00Z',
  },
  {
    id: 'case-005',
    referenceNo: 'AU-CS-INT-2026-005',
    sessionId: 'ses-003',
    studentId: 'usr-014',
    studentName: 'Ali Hassan Shah',
    studentRegNo: '2022-CS-156',
    courseCode: 'CS-201',
    courseName: 'Data Structures',
    classroomName: 'CR-201',
    seatNumber: 3,
    behaviourTypes: [BehaviorType.HeadPoseViolation, BehaviorType.GazeDeviation],
    compositeScore: 0.76,
    status: CaseStatus.Escalated,
    detectionEventId: 'det-005',
    snapshotPath: '/snapshots/ses-003/det-005.jpg',
    teacherNote: 'Repeated head turning towards adjacent student. Persistent behavior throughout exam.',
    teacherId: 'usr-005',
    teacherName: 'Ms. Fatima Zahra',
    hodId: 'usr-002',
    timeline: makeTimeline('case-005', CaseStatus.Escalated),
    createdAt: '2026-09-20T10:45:00Z',
    updatedAt: '2026-09-20T16:30:00Z',
  },
  {
    id: 'case-006',
    referenceNo: 'AU-CS-INT-2026-006',
    sessionId: 'ses-001',
    studentId: 'usr-016',
    studentName: 'Hamza Qureshi',
    studentRegNo: '2022-CS-203',
    courseCode: 'CS-301',
    courseName: 'Database Systems',
    classroomName: 'LH-4',
    seatNumber: 19,
    behaviourTypes: [BehaviorType.LipMovement],
    compositeScore: 0.65,
    status: CaseStatus.PendingReview,
    detectionEventId: 'det-006',
    snapshotPath: '/snapshots/ses-001/det-006.jpg',
    teacherNote: 'Lip movement detected during silent exam. May be reading questions aloud to self.',
    teacherId: 'usr-004',
    teacherName: 'Mr. Usman Tariq',
    timeline: makeTimeline('case-006', CaseStatus.PendingReview),
    createdAt: '2026-09-22T09:30:00Z',
    updatedAt: '2026-09-22T09:30:00Z',
  },
  {
    id: 'case-007',
    referenceNo: 'AU-CS-INT-2026-007',
    sessionId: 'ses-001',
    studentId: 'usr-017',
    studentName: 'Sara Javed',
    studentRegNo: '2023-CS-077',
    courseCode: 'CS-301',
    courseName: 'Database Systems',
    classroomName: 'LH-4',
    seatNumber: 42,
    behaviourTypes: [BehaviorType.PhoneDetected],
    compositeScore: 0.95,
    status: CaseStatus.PendingReview,
    detectionEventId: 'det-007',
    snapshotPath: '/snapshots/ses-001/det-007.jpg',
    teacherNote: 'Phone visible on desk surface. Student asked to remove it.',
    teacherId: 'usr-004',
    teacherName: 'Mr. Usman Tariq',
    timeline: makeTimeline('case-007', CaseStatus.PendingReview),
    createdAt: '2026-09-22T10:05:00Z',
    updatedAt: '2026-09-22T10:05:00Z',
  },
  {
    id: 'case-008',
    referenceNo: 'AU-CS-INT-2026-008',
    sessionId: 'ses-004',
    studentId: 'usr-020',
    studentName: 'Faizan Ahmad',
    studentRegNo: '2022-CS-067',
    courseCode: 'CS-401',
    courseName: 'Artificial Intelligence',
    classroomName: 'LH-4',
    seatNumber: 8,
    behaviourTypes: [BehaviorType.GazeDeviation, BehaviorType.HeadPoseViolation],
    compositeScore: 0.69,
    status: CaseStatus.Dismissed,
    detectionEventId: 'det-008',
    snapshotPath: '/snapshots/ses-004/det-008.jpg',
    teacherNote: 'Brief head movement. Student was stretching, no evidence of cheating.',
    teacherId: 'usr-004',
    teacherName: 'Mr. Usman Tariq',
    hodId: 'usr-002',
    timeline: makeTimeline('case-008', CaseStatus.Dismissed),
    createdAt: '2026-09-21T15:20:00Z',
    updatedAt: '2026-09-21T15:45:00Z',
  },
  {
    id: 'case-009',
    referenceNo: 'AU-SE-INT-2026-009',
    sessionId: 'ses-003',
    studentId: 'usr-015',
    studentName: 'Maryam Asif',
    studentRegNo: '2023-SE-018',
    courseCode: 'CS-201',
    courseName: 'Data Structures',
    classroomName: 'CR-201',
    seatNumber: 11,
    behaviourTypes: [BehaviorType.UnauthorisedObject, BehaviorType.PhoneDetected],
    compositeScore: 0.91,
    status: CaseStatus.Confirmed,
    detectionEventId: 'det-009',
    snapshotPath: '/snapshots/ses-003/det-009.jpg',
    teacherNote: 'Smartwatch and phone both visible. Student warned previously.',
    teacherId: 'usr-005',
    teacherName: 'Ms. Fatima Zahra',
    hodId: 'usr-002',
    penalty: {
      id: 'pen-003',
      caseId: 'case-009',
      type: PenaltyType.MarkDeduction,
      description: '25% mark deduction for possession of electronic devices during examination.',
      issuedBy: 'usr-002',
      issuedByName: 'Prof. Khalid Mehmood',
      noticeReference: 'AU-SE-INT-2026-009',
      createdAt: '2026-09-21T11:00:00Z',
    },
    timeline: makeTimeline('case-009', CaseStatus.Confirmed),
    createdAt: '2026-09-20T11:15:00Z',
    updatedAt: '2026-09-21T11:00:00Z',
  },
  {
    id: 'case-010',
    referenceNo: 'AU-CS-INT-2026-010',
    sessionId: 'ses-001',
    studentId: 'usr-019',
    studentName: 'Amna Rehman',
    studentRegNo: '2023-CS-145',
    courseCode: 'CS-301',
    courseName: 'Database Systems',
    classroomName: 'LH-4',
    seatNumber: 27,
    behaviourTypes: [BehaviorType.GazeDeviation],
    compositeScore: 0.58,
    status: CaseStatus.PendingReview,
    detectionEventId: 'det-010',
    snapshotPath: '/snapshots/ses-001/det-010.jpg',
    teacherNote: 'Brief gaze deviation detected. Low confidence score.',
    teacherId: 'usr-004',
    teacherName: 'Mr. Usman Tariq',
    timeline: makeTimeline('case-010', CaseStatus.PendingReview),
    createdAt: '2026-09-22T10:30:00Z',
    updatedAt: '2026-09-22T10:30:00Z',
  },
];

// ── Detection Events (for Live Monitor) ────

export const detectionEvents: DetectionEvent[] = [
  {
    id: 'det-001',
    sessionId: 'ses-001',
    seatNumber: 14,
    studentId: 'usr-010',
    studentName: 'Ahmed Raza',
    behaviourTypes: [BehaviorType.PhoneDetected],
    perSignal: { [BehaviorType.PhoneDetected]: 0.91 },
    compositeScore: 0.91,
    snapshotPath: '/snapshots/ses-001/det-001.jpg',
    detectedAt: '2026-09-22T09:23:00Z',
    status: 'Confirmed',
  },
  {
    id: 'det-002',
    sessionId: 'ses-001',
    seatNumber: 7,
    studentId: 'usr-011',
    studentName: 'Zainab Malik',
    behaviourTypes: [BehaviorType.GazeDeviation],
    perSignal: { [BehaviorType.GazeDeviation]: 0.68 },
    compositeScore: 0.68,
    snapshotPath: '/snapshots/ses-001/det-002.jpg',
    detectedAt: '2026-09-22T09:28:00Z',
    status: 'Dismissed',
  },
  {
    id: 'det-003',
    sessionId: 'ses-001',
    seatNumber: 22,
    studentId: 'usr-013',
    studentName: 'Hira Nawaz',
    behaviourTypes: [BehaviorType.LipMovement, BehaviorType.HeadPoseViolation],
    perSignal: { [BehaviorType.LipMovement]: 0.82, [BehaviorType.HeadPoseViolation]: 0.71 },
    compositeScore: 0.84,
    snapshotPath: '/snapshots/ses-001/det-003.jpg',
    detectedAt: '2026-09-22T09:35:00Z',
    status: 'New',
  },
  {
    id: 'det-004',
    sessionId: 'ses-001',
    seatNumber: 42,
    studentId: 'usr-017',
    studentName: 'Sara Javed',
    behaviourTypes: [BehaviorType.PhoneDetected],
    perSignal: { [BehaviorType.PhoneDetected]: 0.95 },
    compositeScore: 0.95,
    snapshotPath: '/snapshots/ses-001/det-004.jpg',
    detectedAt: '2026-09-22T09:42:00Z',
    status: 'New',
  },
  {
    id: 'det-005',
    sessionId: 'ses-001',
    seatNumber: 3,
    studentId: 'usr-014',
    studentName: 'Ali Hassan Shah',
    behaviourTypes: [BehaviorType.HeadPoseViolation],
    perSignal: { [BehaviorType.HeadPoseViolation]: 0.74 },
    compositeScore: 0.74,
    snapshotPath: '/snapshots/ses-001/det-005.jpg',
    detectedAt: '2026-09-22T09:50:00Z',
    status: 'Reviewed',
  },
];

// ── Threshold Config ───────────────────────

export const thresholdConfigs: ThresholdConfig[] = [
  {
    id: 'thr-001',
    behaviorType: BehaviorType.GazeDeviation,
    sensitivity: 65,
    weight: 0.15,
    lastCalibrated: '2026-09-01T09:00:00Z',
    calibratedBy: 'Dr. Sadia Rashid',
  },
  {
    id: 'thr-002',
    behaviorType: BehaviorType.HeadPoseViolation,
    sensitivity: 70,
    weight: 0.20,
    lastCalibrated: '2026-09-01T09:00:00Z',
    calibratedBy: 'Dr. Sadia Rashid',
  },
  {
    id: 'thr-003',
    behaviorType: BehaviorType.LipMovement,
    sensitivity: 75,
    weight: 0.20,
    lastCalibrated: '2026-09-01T09:00:00Z',
    calibratedBy: 'Dr. Sadia Rashid',
  },
  {
    id: 'thr-004',
    behaviorType: BehaviorType.PhoneDetected,
    sensitivity: 80,
    weight: 0.30,
    lastCalibrated: '2026-09-01T09:00:00Z',
    calibratedBy: 'Dr. Sadia Rashid',
  },
  {
    id: 'thr-005',
    behaviorType: BehaviorType.UnauthorisedObject,
    sensitivity: 72,
    weight: 0.15,
    lastCalibrated: '2026-09-01T09:00:00Z',
    calibratedBy: 'Dr. Sadia Rashid',
  },
];

// ── Audit Log ──────────────────────────────

export const auditLog: AuditLogEntry[] = [
  {
    id: 'aud-001',
    timestamp: '2026-09-22T09:24:30Z',
    userId: 'usr-004',
    userName: 'Mr. Usman Tariq',
    userRole: Role.Teacher,
    action: 'Case created',
    target: 'case-006',
    details: 'Created case AU-CS-INT-2026-006 from detection event during CS-301 exam',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'aud-002',
    timestamp: '2026-09-22T10:05:00Z',
    userId: 'usr-004',
    userName: 'Mr. Usman Tariq',
    userRole: Role.Teacher,
    action: 'Case created',
    target: 'case-007',
    details: 'Created case AU-CS-INT-2026-007 from detection event during CS-301 exam',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'aud-003',
    timestamp: '2026-09-21T16:00:00Z',
    userId: 'usr-002',
    userName: 'Prof. Khalid Mehmood',
    userRole: Role.HOD,
    action: 'Penalty issued',
    target: 'case-004',
    details: 'Formal Warning issued for case AU-SE-INT-2026-004',
    ipAddress: '192.168.1.12',
  },
  {
    id: 'aud-004',
    timestamp: '2026-09-21T11:00:00Z',
    userId: 'usr-002',
    userName: 'Prof. Khalid Mehmood',
    userRole: Role.HOD,
    action: 'Penalty issued',
    target: 'case-009',
    details: 'Mark Deduction penalty for case AU-SE-INT-2026-009',
    ipAddress: '192.168.1.12',
  },
  {
    id: 'aud-005',
    timestamp: '2026-09-21T10:00:00Z',
    userId: 'usr-010',
    userName: 'Ahmed Raza',
    userRole: Role.Student,
    action: 'Appeal submitted',
    target: 'apl-001',
    details: 'Appeal submitted for case AU-CS-INT-2026-001',
    ipAddress: '10.0.0.89',
  },
  {
    id: 'aud-006',
    timestamp: '2026-09-20T16:30:00Z',
    userId: 'usr-002',
    userName: 'Prof. Khalid Mehmood',
    userRole: Role.HOD,
    action: 'Case escalated',
    target: 'case-005',
    details: 'Case AU-CS-INT-2026-005 escalated to disciplinary committee',
    ipAddress: '192.168.1.12',
  },
  {
    id: 'aud-007',
    timestamp: '2026-09-20T14:20:00Z',
    userId: 'usr-002',
    userName: 'Prof. Khalid Mehmood',
    userRole: Role.HOD,
    action: 'Case dismissed',
    target: 'case-002',
    details: 'Case AU-CS-INT-2026-002 dismissed — insufficient evidence',
    ipAddress: '192.168.1.12',
  },
  {
    id: 'aud-008',
    timestamp: '2026-09-20T09:00:00Z',
    userId: 'usr-005',
    userName: 'Ms. Fatima Zahra',
    userRole: Role.Teacher,
    action: 'Session started',
    target: 'ses-003',
    details: 'Started exam session for CS-201 in CR-201',
    ipAddress: '192.168.1.67',
  },
  {
    id: 'aud-009',
    timestamp: '2026-09-19T14:00:00Z',
    userId: 'usr-001',
    userName: 'Dr. Sadia Rashid',
    userRole: Role.Admin,
    action: 'Threshold updated',
    target: 'thr-004',
    details: 'Phone detection sensitivity increased from 75 to 80',
    ipAddress: '192.168.1.10',
  },
  {
    id: 'aud-010',
    timestamp: '2026-09-19T10:00:00Z',
    userId: 'usr-009',
    userName: 'Mr. Naveed Iqbal',
    userRole: Role.ExamController,
    action: 'Exam scheduled',
    target: 'ses-001',
    details: 'Scheduled CS-301 exam for 2026-09-22 in LH-4',
    ipAddress: '192.168.1.30',
  },
];

// ── Notifications ──────────────────────────

export const notifications: Notification[] = [
  {
    id: 'ntf-001',
    userId: 'usr-002',
    title: 'New case pending review',
    message: 'Case AU-CS-INT-2026-006 requires your review. Lip movement detected during CS-301 exam.',
    type: 'case_update',
    referenceId: 'case-006',
    referenceType: 'case',
    read: false,
    createdAt: '2026-09-22T09:30:00Z',
  },
  {
    id: 'ntf-002',
    userId: 'usr-002',
    title: 'New case pending review',
    message: 'Case AU-CS-INT-2026-007 requires your review. Phone detected during CS-301 exam.',
    type: 'case_update',
    referenceId: 'case-007',
    referenceType: 'case',
    read: false,
    createdAt: '2026-09-22T10:05:00Z',
  },
  {
    id: 'ntf-003',
    userId: 'usr-002',
    title: 'Appeal submitted',
    message: 'Ahmed Raza has submitted an appeal for case AU-CS-INT-2026-001.',
    type: 'appeal',
    referenceId: 'apl-001',
    referenceType: 'appeal',
    read: false,
    createdAt: '2026-09-21T10:00:00Z',
  },
  {
    id: 'ntf-004',
    userId: 'usr-010',
    title: 'Penalty issued',
    message: 'A penalty has been issued for your case AU-CS-INT-2026-001. You may submit an appeal.',
    type: 'penalty',
    referenceId: 'case-001',
    referenceType: 'case',
    read: true,
    createdAt: '2026-09-20T15:00:00Z',
  },
  {
    id: 'ntf-005',
    userId: 'usr-004',
    title: 'Session starting soon',
    message: 'Your exam session for CS-301 in LH-4 begins in 15 minutes.',
    type: 'system',
    referenceId: 'ses-001',
    referenceType: 'session',
    read: true,
    createdAt: '2026-09-22T08:45:00Z',
  },
  {
    id: 'ntf-006',
    userId: 'usr-004',
    title: 'High-confidence alert',
    message: 'Phone detected at seat 42 with 95% confidence during CS-301 exam.',
    type: 'alert',
    referenceId: 'det-004',
    referenceType: 'session',
    read: false,
    createdAt: '2026-09-22T09:42:00Z',
  },
];

// ── Exam Schedule ──────────────────────────

export const examSchedule: ExamScheduleEntry[] = [
  {
    id: 'exam-001',
    courseCode: 'CS-301',
    courseName: 'Database Systems',
    department: 'Computer Science',
    date: '2026-09-22',
    startTime: '09:00',
    endTime: '12:00',
    classroomId: 'cls-001',
    classroomName: 'LH-4',
    invigilatorId: 'usr-004',
    invigilatorName: 'Mr. Usman Tariq',
    status: SessionStatus.InProgress,
  },
  {
    id: 'exam-002',
    courseCode: 'SE-410',
    courseName: 'Software Architecture',
    department: 'Software Engineering',
    date: '2026-09-22',
    startTime: '14:00',
    endTime: '17:00',
    classroomId: 'cls-002',
    classroomName: 'LH-7',
    invigilatorId: 'usr-006',
    invigilatorName: 'Dr. Hassan Ali',
    status: SessionStatus.Scheduled,
  },
  {
    id: 'exam-003',
    courseCode: 'CS-201',
    courseName: 'Data Structures',
    department: 'Computer Science',
    date: '2026-09-20',
    startTime: '09:00',
    endTime: '12:00',
    classroomId: 'cls-003',
    classroomName: 'CR-201',
    invigilatorId: 'usr-005',
    invigilatorName: 'Ms. Fatima Zahra',
    status: SessionStatus.Completed,
  },
  {
    id: 'exam-004',
    courseCode: 'CS-401',
    courseName: 'Artificial Intelligence',
    department: 'Computer Science',
    date: '2026-09-21',
    startTime: '14:00',
    endTime: '17:00',
    classroomId: 'cls-001',
    classroomName: 'LH-4',
    invigilatorId: 'usr-004',
    invigilatorName: 'Mr. Usman Tariq',
    status: SessionStatus.Completed,
  },
  {
    id: 'exam-005',
    courseCode: 'SE-320',
    courseName: 'Software Testing',
    department: 'Software Engineering',
    date: '2026-09-23',
    startTime: '09:00',
    endTime: '11:00',
    classroomId: 'cls-005',
    classroomName: 'Lab-3',
    invigilatorId: 'usr-008',
    invigilatorName: 'Mr. Bilal Asghar',
    status: SessionStatus.Scheduled,
  },
  {
    id: 'exam-006',
    courseCode: 'CS-101',
    courseName: 'Introduction to Computing',
    department: 'Computer Science',
    date: '2026-09-23',
    startTime: '09:00',
    endTime: '12:00',
    classroomId: 'cls-001',
    classroomName: 'LH-4',
    invigilatorId: 'usr-005',
    invigilatorName: 'Ms. Fatima Zahra',
    status: SessionStatus.Scheduled,
  },
  {
    id: 'exam-007',
    courseCode: 'CS-501',
    courseName: 'Machine Learning',
    department: 'Computer Science',
    date: '2026-09-24',
    startTime: '09:00',
    endTime: '12:00',
    classroomId: 'cls-006',
    classroomName: 'CR-105',
    status: SessionStatus.Scheduled,
    hasConflict: true,
    conflictDetails: 'No invigilator assigned',
  },
  {
    id: 'exam-008',
    courseCode: 'SE-201',
    courseName: 'Software Design',
    department: 'Software Engineering',
    date: '2026-09-24',
    startTime: '14:00',
    endTime: '17:00',
    classroomId: 'cls-002',
    classroomName: 'LH-7',
    invigilatorId: 'usr-006',
    invigilatorName: 'Dr. Hassan Ali',
    status: SessionStatus.Scheduled,
  },
];

// ── Invigilator Assignments ────────────────

export const invigilatorAssignments: InvigilatorAssignment[] = [
  {
    id: 'asn-001',
    examId: 'exam-001',
    teacherId: 'usr-004',
    teacherName: 'Mr. Usman Tariq',
    department: 'Computer Science',
    courseCode: 'CS-301',
    date: '2026-09-22',
    startTime: '09:00',
    endTime: '12:00',
    classroomName: 'LH-4',
    status: 'Assigned',
  },
  {
    id: 'asn-002',
    examId: 'exam-002',
    teacherId: 'usr-006',
    teacherName: 'Dr. Hassan Ali',
    department: 'Software Engineering',
    courseCode: 'SE-410',
    date: '2026-09-22',
    startTime: '14:00',
    endTime: '17:00',
    classroomName: 'LH-7',
    status: 'Assigned',
  },
  {
    id: 'asn-003',
    examId: 'exam-005',
    teacherId: 'usr-008',
    teacherName: 'Mr. Bilal Asghar',
    department: 'Software Engineering',
    courseCode: 'SE-320',
    date: '2026-09-23',
    startTime: '09:00',
    endTime: '11:00',
    classroomName: 'Lab-3',
    status: 'Assigned',
  },
  {
    id: 'asn-004',
    examId: 'exam-006',
    teacherId: 'usr-005',
    teacherName: 'Ms. Fatima Zahra',
    department: 'Computer Science',
    courseCode: 'CS-101',
    date: '2026-09-23',
    startTime: '09:00',
    endTime: '12:00',
    classroomName: 'LH-4',
    status: 'Assigned',
  },
  {
    id: 'asn-005',
    examId: 'exam-008',
    teacherId: 'usr-006',
    teacherName: 'Dr. Hassan Ali',
    department: 'Software Engineering',
    courseCode: 'SE-201',
    date: '2026-09-24',
    startTime: '14:00',
    endTime: '17:00',
    classroomName: 'LH-7',
    status: 'Assigned',
  },
  {
    id: 'asn-006',
    examId: 'exam-007',
    teacherId: 'usr-004',
    teacherName: 'Mr. Usman Tariq',
    department: 'Computer Science',
    courseCode: 'CS-501',
    date: '2026-09-24',
    startTime: '09:00',
    endTime: '12:00',
    classroomName: 'CR-105',
    status: 'Available',
  },
];
